import { ImageResponse } from "next/og";
import { readFileSync } from "node:fs";
import { join } from "node:path";

// 180×180 apple-touch icon (iOS ignores SVG favicons). Generated by next/og so
// no binary asset is committed. Served at /apple-icon and auto-linked by Next.
export const runtime = "nodejs";
export const size = { width: 180, height: 180 };
export const contentType = "image/png";

const treeSrc = `data:image/png;base64,${readFileSync(
  join(process.cwd(), "public/sprites/AppleTree_8.png"),
).toString("base64")}`;

export default function AppleIcon() {
  return new ImageResponse(
    <div
      style={{
        width: "100%",
        height: "100%",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        backgroundColor: "#faf5ea",
      }}
    >
      <img src={treeSrc} width={138} height={150} style={{ objectFit: "contain" }} alt="" />
    </div>,
    { ...size },
  );
}
