-- ⚠️ 本文件由 Token-Forest/tools/gen_name_guard_sql.py 生成,不要手改。
-- 规则的唯一事实源是 Token-Forest 的 src/names.py 与 resources/wordlist/。
-- 手改这里会造成「客户端放行、服务端拒绝」的静默失败 —— 正是这套东西要消灭的症状。

-- Migration: 0014_banned_words_seed
-- 词表数据。改 Token-Forest/resources/wordlist/ 后重跑生成脚本、只重放这个文件即可。
--
-- 词表条目 430 条,白名单 60 条。
-- 词条已经过 normalize_name() 的归一化(小写、繁转简、同形字/leet 还原、去分隔符),
-- 所以这里看到的形态和原始词表文件不完全一样 —— 那是对的,两侧必须在同一坐标系里比对。

-- 全量替换:先清空再灌,避免删掉的词还留在库里
truncate table public.banned_words;
truncate table public.allowed_names;

insert into public.banned_words (word, category, match_mode) values
  ('arsehole', 'abuse', 'latin'),
  ('asshole', 'abuse', 'latin'),
  ('av女优', 'porn', 'cjk'),
  ('bastard', 'abuse', 'latin'),
  ('bdsm', 'porn', 'latin'),
  ('bitch', 'abuse', 'latin'),
  ('blowjob', 'porn', 'latin'),
  ('bollocks', 'abuse', 'latin'),
  ('boobs', 'porn', 'latin'),
  ('bukkake', 'porn', 'latin'),
  ('bullshit', 'abuse', 'latin'),
  ('chinaman', 'hate', 'latin'),
  ('chingchong', 'hate', 'latin'),
  ('chink', 'hate', 'latin'),
  ('cock', 'porn', 'latin'),
  ('creampie', 'porn', 'latin'),
  ('cumshot', 'porn', 'latin'),
  ('cunt', 'porn', 'latin'),
  ('deepthroat', 'porn', 'latin'),
  ('dick', 'porn', 'latin'),
  ('dildo', 'porn', 'latin'),
  ('dipshit', 'abuse', 'latin'),
  ('douchebag', 'abuse', 'latin'),
  ('dumbass', 'abuse', 'latin'),
  ('faggot', 'hate', 'latin'),
  ('fagot', 'hate', 'latin'),
  ('fatass', 'abuse', 'latin'),
  ('fck', 'porn', 'latin'),
  ('fuck', 'porn', 'latin'),
  ('gangbang', 'porn', 'latin'),
  ('gtfo', 'abuse', 'latin'),
  ('handjb', 'porn', 'latin'),
  ('handjob', 'porn', 'latin'),
  ('heilhitler', 'hate', 'latin'),
  ('hentai', 'porn', 'latin'),
  ('hitler', 'hate', 'latin'),
  ('holohoax', 'hate', 'latin'),
  ('hooker', 'porn', 'latin'),
  ('iabb', 'hate', 'latin'),
  ('idiot', 'abuse', 'latin'),
  ('imbecile', 'abuse', 'latin'),
  ('incest', 'porn', 'latin'),
  ('isis', 'violence', 'latin'),
  ('jackass', 'abuse', 'latin'),
  ('jizz', 'porn', 'latin'),
  ('kike', 'hate', 'latin'),
  ('kkk', 'hate', 'latin'),
  ('kys', 'abuse', 'latin'),
  ('k粉', 'violence', 'cjk'),
  ('loli', 'porn', 'latin'),
  ('loser', 'abuse', 'latin'),
  ('milf', 'porn', 'latin'),
  ('molest', 'porn', 'latin'),
  ('moron', 'abuse', 'latin'),
  ('motherfucker', 'porn', 'latin'),
  ('nazi', 'hate', 'latin'),
  ('negroid', 'hate', 'latin'),
  ('nigga', 'hate', 'latin'),
  ('nigger', 'hate', 'latin'),
  ('niggr', 'hate', 'latin'),
  ('nsfw', 'porn', 'latin'),
  ('nympho', 'porn', 'latin'),
  ('orgasm', 'porn', 'latin'),
  ('pedo', 'porn', 'latin'),
  ('penis', 'porn', 'latin'),
  ('porn', 'porn', 'latin'),
  ('porno', 'porn', 'latin'),
  ('prick', 'abuse', 'latin'),
  ('prostitute', 'porn', 'latin'),
  ('pussy', 'porn', 'latin'),
  ('raghead', 'hate', 'latin'),
  ('rape', 'porn', 'latin'),
  ('retard', 'abuse', 'latin'),
  ('retarded', 'abuse', 'latin'),
  ('scumbag', 'abuse', 'latin'),
  ('shithead', 'abuse', 'latin'),
  ('shota', 'porn', 'latin'),
  ('slut', 'porn', 'latin'),
  ('stfu', 'abuse', 'latin'),
  ('tits', 'porn', 'latin'),
  ('titty', 'porn', 'latin'),
  ('tnt炸药', 'violence', 'cjk'),
  ('tosser', 'abuse', 'latin'),
  ('towelhead', 'hate', 'latin'),
  ('twat', 'abuse', 'latin'),
  ('vagina', 'porn', 'latin'),
  ('wanker', 'abuse', 'latin'),
  ('whitepower', 'hate', 'latin'),
  ('whitepride', 'hate', 'latin'),
  ('whore', 'porn', 'latin'),
  ('xxx', 'porn', 'latin'),
  ('一夜情', 'porn', 'cjk'),
  ('一边一国', 'politics', 'cjk'),
  ('三k党', 'hate', 'cjk'),
  ('三唑仑', 'violence', 'cjk'),
  ('三级片', 'porn', 'cjk'),
  ('三退保平安', 'politics', 'cjk'),
  ('上门服务', 'porn', 'cjk'),
  ('下体', 'porn', 'cjk'),
  ('下贱', 'abuse', 'cjk'),
  ('不得好死', 'abuse', 'cjk'),
  ('东伊运', 'politics', 'cjk'),
  ('东方闪电', 'politics', 'cjk'),
  ('东突厥斯坦', 'politics', 'cjk'),
  ('东突恐怖', 'violence', 'cjk'),
  ('中出', 'porn', 'cjk'),
  ('中国猪', 'hate', 'cjk'),
  ('习包子', 'politics', 'cjk'),
  ('习特勒', 'politics', 'cjk'),
  ('习近平', 'politics', 'cjk'),
  ('买枪', 'violence', 'cjk'),
  ('乱伦', 'porn', 'cjk'),
  ('乳交', 'porn', 'cjk'),
  ('二逼', 'porn', 'cjk'),
  ('五毛党', 'abuse', 'cjk'),
  ('交配', 'porn', 'cjk'),
  ('人渣', 'abuse', 'cjk'),
  ('人肉炸弹', 'violence', 'cjk'),
  ('仿真枪', 'violence', 'cjk'),
  ('低等民族', 'hate', 'cjk'),
  ('你全家', 'abuse', 'cjk'),
  ('你妈死', 'abuse', 'cjk'),
  ('你妈的', 'porn', 'cjk'),
  ('倭奴', 'hate', 'cjk'),
  ('倭寇', 'hate', 'cjk'),
  ('做爱', 'porn', 'cjk'),
  ('偷拍', 'porn', 'cjk'),
  ('傻叉', 'abuse', 'cjk'),
  ('傻子', 'abuse', 'cjk'),
  ('傻缺', 'abuse', 'cjk'),
  ('傻逼', 'porn', 'cjk'),
  ('光复香港', 'politics', 'cjk'),
  ('兔崽子', 'abuse', 'cjk'),
  ('全家死', 'abuse', 'cjk'),
  ('全能神', 'politics', 'cjk'),
  ('全裸', 'porn', 'cjk'),
  ('八九学潮', 'politics', 'cjk'),
  ('八九民运', 'politics', 'cjk'),
  ('六四事件', 'politics', 'cjk'),
  ('六四天安门', 'politics', 'cjk'),
  ('共产党滚', 'politics', 'cjk'),
  ('共匪', 'politics', 'cjk'),
  ('共惨党', 'politics', 'cjk'),
  ('共狗', 'politics', 'cjk'),
  ('共铲党', 'politics', 'cjk'),
  ('兽交', 'porn', 'cjk'),
  ('内射', 'porn', 'cjk'),
  ('军火交易', 'violence', 'cjk'),
  ('冰毒', 'violence', 'cjk'),
  ('几把', 'porn', 'cjk'),
  ('分尸', 'violence', 'cjk'),
  ('制作炸弹', 'violence', 'cjk'),
  ('制毒', 'violence', 'cjk'),
  ('割腕自杀', 'violence', 'cjk'),
  ('劣等人种', 'hate', 'cjk'),
  ('劣等民族', 'hate', 'cjk'),
  ('劣等种族', 'hate', 'cjk'),
  ('包养', 'porn', 'cjk'),
  ('包子习', 'politics', 'cjk'),
  ('包皮', 'porn', 'cjk'),
  ('半裸', 'porn', 'cjk'),
  ('卖枪', 'violence', 'cjk'),
  ('卖淫', 'porn', 'cjk'),
  ('卧槽泥马', 'porn', 'cjk'),
  ('印度阿三', 'hate', 'cjk'),
  ('去你妈', 'porn', 'cjk'),
  ('去死吧', 'abuse', 'cjk'),
  ('口交', 'porn', 'cjk'),
  ('可卡因', 'violence', 'cjk'),
  ('台湾独立', 'politics', 'cjk'),
  ('台独', 'politics', 'cjk'),
  ('吊毛', 'porn', 'cjk'),
  ('吗啡', 'violence', 'cjk'),
  ('听话水', 'violence', 'cjk'),
  ('吸大麻', 'violence', 'cjk'),
  ('吸毒', 'violence', 'cjk'),
  ('周恩来', 'politics', 'cjk'),
  ('呼喊派', 'politics', 'cjk'),
  ('咖喱味', 'hate', 'cjk'),
  ('售枪', 'violence', 'cjk'),
  ('啥比', 'porn', 'cjk'),
  ('喷子', 'abuse', 'cjk'),
  ('土共', 'politics', 'cjk'),
  ('土制枪', 'violence', 'cjk'),
  ('土制炸弹', 'violence', 'cjk'),
  ('土肥圆', 'abuse', 'cjk'),
  ('圣战组织', 'violence', 'cjk'),
  ('圣母婊', 'abuse', 'cjk'),
  ('坦克人', 'politics', 'cjk'),
  ('基佬', 'hate', 'cjk'),
  ('基地组织', 'violence', 'cjk'),
  ('塔利班', 'violence', 'cjk'),
  ('处女膜', 'porn', 'cjk'),
  ('外围女', 'porn', 'cjk'),
  ('大麻叶', 'violence', 'cjk'),
  ('天安门事件', 'politics', 'cjk'),
  ('天灭中共', 'politics', 'cjk'),
  ('奸淫', 'porn', 'cjk'),
  ('妈了个逼', 'porn', 'cjk'),
  ('妈死了', 'abuse', 'cjk'),
  ('妈的逼', 'porn', 'cjk'),
  ('妓女', 'porn', 'cjk'),
  ('妓院', 'porn', 'cjk'),
  ('娘炮', 'hate', 'cjk'),
  ('娼妓', 'porn', 'cjk'),
  ('婊子', 'porn', 'cjk'),
  ('嫖娼', 'porn', 'cjk'),
  ('孙子诶', 'abuse', 'cjk'),
  ('安非他命', 'violence', 'cjk'),
  ('射精', 'porn', 'cjk'),
  ('小姐上门', 'porn', 'cjk'),
  ('小日本', 'hate', 'cjk'),
  ('尼哥', 'hate', 'cjk'),
  ('屌丝', 'porn', 'cjk'),
  ('屠杀平民', 'violence', 'cjk'),
  ('希特勒', 'hate', 'cjk'),
  ('干你', 'porn', 'cjk'),
  ('干死你', 'porn', 'cjk'),
  ('床破习', 'politics', 'cjk'),
  ('强奸', 'porn', 'cjk'),
  ('心机婊', 'abuse', 'cjk'),
  ('性交', 'porn', 'cjk'),
  ('性爱', 'porn', 'cjk'),
  ('恋童', 'porn', 'cjk'),
  ('恐怖分子', 'violence', 'cjk'),
  ('恐怖组织', 'violence', 'cjk'),
  ('恐怖袭击', 'violence', 'cjk'),
  ('恶党', 'politics', 'cjk'),
  ('情色', 'porn', 'cjk'),
  ('成人片', 'porn', 'cjk'),
  ('手淫', 'porn', 'cjk'),
  ('打倒共产党', 'politics', 'cjk'),
  ('打飞机', 'porn', 'cjk'),
  ('抿主', 'politics', 'cjk'),
  ('拱铲党', 'politics', 'cjk'),
  ('指交', 'porn', 'cjk'),
  ('按摩服务', 'porn', 'cjk'),
  ('援交', 'porn', 'cjk'),
  ('摇头丸', 'violence', 'cjk'),
  ('撒币', 'porn', 'cjk'),
  ('撸管', 'porn', 'cjk'),
  ('操你', 'porn', 'cjk'),
  ('操死', 'porn', 'cjk'),
  ('支那', 'hate', 'cjk'),
  ('支那人', 'hate', 'cjk'),
  ('敏主', 'politics', 'cjk'),
  ('教你自杀', 'violence', 'cjk'),
  ('断子绝孙族', 'hate', 'cjk'),
  ('新疆独立', 'politics', 'cjk'),
  ('新纳粹', 'hate', 'cjk'),
  ('无码', 'porn', 'cjk'),
  ('日你', 'porn', 'cjk'),
  ('日本鬼子', 'hate', 'cjk'),
  ('时代革命', 'politics', 'cjk'),
  ('智障', 'abuse', 'cjk'),
  ('有码', 'porn', 'cjk'),
  ('本子里番', 'porn', 'cjk'),
  ('朱镕基', 'politics', 'cjk'),
  ('杀人犯', 'violence', 'cjk'),
  ('杀人狂', 'violence', 'cjk'),
  ('杂碎', 'abuse', 'cjk'),
  ('杂种', 'abuse', 'cjk'),
  ('李克强', 'politics', 'cjk'),
  ('李洪志', 'politics', 'cjk'),
  ('杜冷丁', 'violence', 'cjk'),
  ('杠精', 'abuse', 'cjk'),
  ('枪支弹药', 'violence', 'cjk'),
  ('棒子国', 'hate', 'cjk'),
  ('死全家', 'abuse', 'cjk'),
  ('死变态', 'hate', 'cjk'),
  ('死基佬', 'hate', 'cjk'),
  ('死妈', 'abuse', 'cjk'),
  ('死爹', 'abuse', 'cjk'),
  ('死胖子', 'abuse', 'cjk'),
  ('殃视', 'politics', 'cjk'),
  ('残废', 'abuse', 'cjk'),
  ('毒贩', 'violence', 'cjk'),
  ('毛泽东', 'politics', 'cjk'),
  ('毛片', 'porn', 'cjk'),
  ('毛贼东', 'politics', 'cjk'),
  ('民猪', 'politics', 'cjk'),
  ('民珠', 'politics', 'cjk'),
  ('水军', 'abuse', 'cjk'),
  ('江泽民', 'politics', 'cjk'),
  ('江泽民同志', 'politics', 'cjk'),
  ('江猪', 'politics', 'cjk'),
  ('江贼', 'politics', 'cjk'),
  ('沙比', 'porn', 'cjk'),
  ('沙漠邪教', 'hate', 'cjk'),
  ('沙雕', 'abuse', 'cjk'),
  ('法轮功', 'politics', 'cjk'),
  ('法轮大法', 'politics', 'cjk'),
  ('浑蛋', 'abuse', 'cjk'),
  ('浪货', 'porn', 'cjk'),
  ('海洛因', 'violence', 'cjk'),
  ('淫乱', 'porn', 'cjk'),
  ('淫妇', 'porn', 'cjk'),
  ('淫娃', 'porn', 'cjk'),
  ('淫荡', 'porn', 'cjk'),
  ('淫魔', 'porn', 'cjk'),
  ('混蛋', 'abuse', 'cjk'),
  ('混账', 'abuse', 'cjk'),
  ('清国奴', 'hate', 'cjk'),
  ('渣滓', 'abuse', 'cjk'),
  ('温家宝', 'politics', 'cjk'),
  ('港独', 'politics', 'cjk'),
  ('滚犊子', 'abuse', 'cjk'),
  ('滚粗', 'abuse', 'cjk'),
  ('潮吹', 'porn', 'cjk'),
  ('灭共', 'politics', 'cjk'),
  ('灭绝人种', 'hate', 'cjk'),
  ('灭绝犹太', 'hate', 'cjk'),
  ('灭门惨案', 'violence', 'cjk'),
  ('炸药配方', 'violence', 'cjk'),
  ('烧死犹太', 'hate', 'cjk'),
  ('热比娅', 'politics', 'cjk'),
  ('煞笔', 'porn', 'cjk'),
  ('牛逼', 'porn', 'cjk'),
  ('牲口', 'abuse', 'cjk'),
  ('特殊服务', 'porn', 'cjk'),
  ('犹太猪', 'hate', 'cjk'),
  ('犹猪', 'hate', 'cjk'),
  ('狗东西', 'abuse', 'cjk'),
  ('狗娘养', 'abuse', 'cjk'),
  ('狗崽子', 'abuse', 'cjk'),
  ('狗杂种', 'abuse', 'cjk'),
  ('狗腿子', 'abuse', 'cjk'),
  ('猫则东', 'politics', 'cjk'),
  ('王八羔', 'abuse', 'cjk'),
  ('王八蛋', 'abuse', 'cjk'),
  ('甲基安非他明', 'violence', 'cjk'),
  ('畜牲', 'abuse', 'cjk'),
  ('畜生', 'abuse', 'cjk'),
  ('疆独', 'politics', 'cjk'),
  ('真善忍', 'politics', 'cjk'),
  ('睾丸', 'porn', 'cjk'),
  ('矮矬穷', 'abuse', 'cjk'),
  ('硝化甘油', 'violence', 'cjk'),
  ('碎尸', 'violence', 'cjk'),
  ('神仙水', 'violence', 'cjk'),
  ('福利姬', 'porn', 'cjk'),
  ('种族清洗', 'hate', 'cjk'),
  ('种族灭绝', 'hate', 'cjk'),
  ('穆黑', 'hate', 'cjk'),
  ('精液', 'porn', 'cjk'),
  ('约死群', 'violence', 'cjk'),
  ('纳粹', 'hate', 'cjk'),
  ('细近平', 'politics', 'cjk'),
  ('维尼习', 'politics', 'cjk'),
  ('绿教', 'hate', 'cjk'),
  ('绿茶婊', 'abuse', 'cjk'),
  ('群交', 'porn', 'cjk'),
  ('肏你', 'porn', 'cjk'),
  ('肛交', 'porn', 'cjk'),
  ('胡耀邦', 'politics', 'cjk'),
  ('胡锦涛', 'politics', 'cjk'),
  ('脑残', 'abuse', 'cjk'),
  ('脑瘫', 'abuse', 'cjk'),
  ('脱光', 'porn', 'cjk'),
  ('脱衣', 'porn', 'cjk'),
  ('自制枪', 'violence', 'cjk'),
  ('自制炸弹', 'violence', 'cjk'),
  ('自慰', 'porn', 'cjk'),
  ('自杀式袭击', 'violence', 'cjk'),
  ('自杀方法', 'violence', 'cjk'),
  ('臭傻', 'abuse', 'cjk'),
  ('臭婊', 'abuse', 'cjk'),
  ('色情', 'porn', 'cjk'),
  ('艹你', 'porn', 'cjk'),
  ('苶逼', 'porn', 'cjk'),
  ('草你', 'porn', 'cjk'),
  ('草你妈', 'abuse', 'cjk'),
  ('草死', 'porn', 'cjk'),
  ('草泥马', 'porn', 'cjk'),
  ('萝莉控', 'porn', 'cjk'),
  ('蒙独', 'politics', 'cjk'),
  ('藏独', 'politics', 'cjk'),
  ('血水圣灵', 'politics', 'cjk'),
  ('装逼', 'porn', 'cjk'),
  ('裸体', 'porn', 'cjk'),
  ('裸照', 'porn', 'cjk'),
  ('裸聊', 'porn', 'cjk'),
  ('西藏独立', 'politics', 'cjk'),
  ('观音法门', 'politics', 'cjk'),
  ('败类', 'abuse', 'cjk'),
  ('贩毒', 'violence', 'cjk'),
  ('贱人', 'porn', 'cjk'),
  ('贱种', 'abuse', 'cjk'),
  ('贱货', 'porn', 'cjk'),
  ('赤匪', 'politics', 'cjk'),
  ('赵紫阳', 'politics', 'cjk'),
  ('足交', 'porn', 'cjk'),
  ('轮奸', 'porn', 'cjk'),
  ('辱华', 'hate', 'cjk'),
  ('达赖喇嘛', 'politics', 'cjk'),
  ('迷奸', 'porn', 'cjk'),
  ('迷魂药', 'violence', 'cjk'),
  ('退党退团', 'politics', 'cjk'),
  ('遥控炸弹', 'violence', 'cjk'),
  ('邓小平', 'politics', 'cjk'),
  ('邪党', 'politics', 'cjk'),
  ('里番', 'porn', 'cjk'),
  ('键盘侠', 'abuse', 'cjk'),
  ('门徒会', 'politics', 'cjk'),
  ('阳具', 'porn', 'cjk'),
  ('阴唇', 'porn', 'cjk'),
  ('阴茎', 'porn', 'cjk'),
  ('阴蒂', 'porn', 'cjk'),
  ('阴道', 'porn', 'cjk'),
  ('阴部', 'porn', 'cjk'),
  ('雷管', 'violence', 'cjk'),
  ('韩国棒子', 'hate', 'cjk'),
  ('颜射', 'porn', 'cjk'),
  ('香港独立', 'politics', 'cjk'),
  ('骚货', 'porn', 'cjk'),
  ('骚逼', 'porn', 'cjk'),
  ('高丽棒子', 'hate', 'cjk'),
  ('鬼子兵', 'hate', 'cjk'),
  ('鸡巴', 'porn', 'cjk'),
  ('鸡鸡', 'porn', 'cjk'),
  ('鸦片', 'violence', 'cjk'),
  ('麻古', 'violence', 'cjk'),
  ('黄片', 'porn', 'cjk'),
  ('黄皮猴', 'hate', 'cjk'),
  ('黄皮肤猪', 'hate', 'cjk'),
  ('黑猴子', 'hate', 'cjk'),
  ('黑粉', 'abuse', 'cjk'),
  ('黑鬼', 'hate', 'cjk'),
  ('龟头', 'porn', 'cjk'),
  ('龟孙子', 'abuse', 'cjk')
on conflict (word) do update
  set category = excluded.category, match_mode = excluded.match_mode;

insert into public.allowed_names (name) values
  ('analytics'),
  ('assistant'),
  ('cockburn'),
  ('cockcroft'),
  ('cockpit'),
  ('cocktail'),
  ('dickens'),
  ('dickinson'),
  ('dickson'),
  ('fukuda'),
  ('fukui'),
  ('fukuoka'),
  ('japan'),
  ('kyle'),
  ('kyson'),
  ('lolita'),
  ('nazim'),
  ('nazir'),
  ('nazira'),
  ('niger'),
  ('nigeria'),
  ('pakistan'),
  ('pedro'),
  ('penistone'),
  ('raccoon'),
  ('raphael'),
  ('scunthorpe'),
  ('spice'),
  ('titan'),
  ('titanic'),
  ('title'),
  ('vandyke'),
  ('上海'),
  ('中国人'),
  ('乌鲁木齐'),
  ('佛教徒'),
  ('内蒙古'),
  ('北京'),
  ('华人'),
  ('台湾'),
  ('回族'),
  ('基督徒'),
  ('天主教徒'),
  ('拉萨'),
  ('新疆'),
  ('无神论者'),
  ('汉族'),
  ('满族'),
  ('澳门'),
  ('犹太'),
  ('犹太人'),
  ('白人'),
  ('穆斯林'),
  ('维吾尔族'),
  ('蒙古族'),
  ('藏族'),
  ('西藏'),
  ('道教徒'),
  ('香港'),
  ('黑人')
on conflict (name) do nothing;
